"""
mapear_entidades_pte.py
=======================
Este script adiciona el Código IES o Código DANE oficial a las entidades presupuestales
del PTE. Limpia problemas de codificación introducidos por la API y prepara la dimensión
para poder ser cruzada posteriormente con los datasets educativos (SNIES / ICFES).
"""

import pandas as pd
from pathlib import Path
import logging

logging.basicConfig(level=logging.INFO, format="%(levelname)s | %(message)s")
logger = logging.getLogger(__name__)

BASE_DIR = Path(__file__).parent.parent.parent
DIM_ENTIDAD_PATH = BASE_DIR / "datos" / "processed" / "pte" / "dimensiones" / "dim_entidad.parquet"

# Diccionario maestro uniendo nombre_sucio -> nombre_limpio, codigo_ies
# Si es un ministerio o entidad que no sea IES (como Ministerio de Educación), 
# asignaremos IES=0 o un código DANE genérico si aplica. 
MAPA_ENTIDADES = {
    # Nombres Limpios Manuales y Entidades de Gobierno
    'MINISTERIO EDUCACION NACIONAL - GESTION GENERAL': ('MINISTERIO DE EDUCACION NACIONAL', '0'),
    'UNIDAD ADMINISTRATIVA ESPECIAL DE ALIMENTACION ESCOLAR': ('UNIDAD ADMINISTRATIVA DE ALIMENTACION ESCOLAR', '0'),
    'ESCUELA TECNOLOGICA INSTITUTO TECNICO CENTRAL': ('ESCUELA TECNOLOGICA INSTITUTO TECNICO CENTRAL', '3109'),
    'INSTITUTO NACIONAL DE FORMACION TECNICA PROFESIONAL DE SAN ANDRES Y PROVIDENCIA': ('INFOTEP SAN ANDRES', '4106'),
    'INSTITUTO NACIONAL DE FORMACION TECNICA PROFESIONAL DE SAN JUAN DEL CESAR': ('INFOTEP SAN JUAN DEL CESAR', '4105'),
    'INSTITUTO TECNICO NACIONAL DE COMERCIO SIMON RODRIGUEZ DE CALI': ('INTENALCO', '3108'),
    'INSTITUTO TOLIMENSE DE FORMACION TECNICA PROFESIONAL': ('ITFIP', '3107'),
    
    # Universidades Limpias (De los Excels)
    'UNIVERSIDADES PUBLICAS - UNIVERSIDAD COLEGIO MAYOR DE CUNDINAMARCA': ('UNIVERSIDAD COLEGIO MAYOR DE CUNDINAMARCA', '3106'),
    'UNIVERSIDADES PUBLICAS - UNIVERSIDAD DE CALDAS': ('UNIVERSIDAD DE CALDAS', '1103'),
    'UNIVERSIDADES PUBLICAS - UNIVERSIDAD DE CORDOBA': ('UNIVERSIDAD DE CORDOBA', '1114'),
    'UNIVERSIDADES PUBLICAS - UNIVERSIDAD DE LA AMAZONIA': ('UNIVERSIDAD DE LA AMAZONIA', '1120'),
    'UNIVERSIDADES PUBLICAS - UNIVERSIDAD DE LOS LLANOS': ('UNIVERSIDAD DE LOS LLANOS', '1117'),
    'UNIVERSIDADES PUBLICAS - UNIVERSIDAD DEL CAUCA': ('UNIVERSIDAD DEL CAUCA', '1102'),
    'UNIVERSIDADES PUBLICAS - UNIVERSIDAD DEL PACIFICO': ('UNIVERSIDAD DEL PACIFICO', '1122'),
    'UNIVERSIDADES PUBLICAS - UNIVERSIDAD NACIONAL ABIERTA Y A DISTANCIA UNAD': ('UNIVERSIDAD NACIONAL ABIERTA Y A DISTANCIA', '2102'),
    'UNIVERSIDADES PUBLICAS - UNIVERSIDAD NACIONAL DE COLOMBIA': ('UNIVERSIDAD NACIONAL DE COLOMBIA', '1101'),
    'UNIVERSIDADES PUBLICAS - UNIVERSIDAD PEDAGOGICA NACIONAL': ('UNIVERSIDAD PEDAGOGICA NACIONAL', '1105'),
    'UNIVERSIDADES PUBLICAS - UNIVERSIDAD PEDAGOGICA Y TECNOLOGICA DE COLOMBIA': ('UNIVERSIDAD PEDAGOGICA Y TECNOLOGICA DE COLOMBIA', '1106'),
    'UNIVERSIDADES PUBLICAS - UNIVERSIDAD POPULAR DEL CESAR': ('UNIVERSIDAD POPULAR DEL CESAR', '1118'),
    'UNIVERSIDADES PUBLICAS - UNIVERSIDAD SURCOLOMBIANA': ('UNIVERSIDAD SURCOLOMBIANA', '1113'),
    'UNIVERSIDADES PUBLICAS - UNIVERSIDAD TECNOLOGICA DE PEREIRA': ('UNIVERSIDAD TECNOLOGICA DE PEREIRA', '1104'),
    'UNIVERSIDADES PUBLICAS - UNIVERSIDAD TECNOLOGICA DEL CHOCO DIEGO LUIS CORDOBA': ('UNIVERSIDAD TECNOLOGICA DEL CHOCO', '1115'),

    # Nombres Sucios de la API Socrata (Con Mojibake)
    'UNIVERSIDADES PBLICAS - UNIVERSIDAD AUTNOMA INDGENA INTERCULTURAL UAIIN CRIC': ('UNIVERSIDAD AUTONOMA INDIGENA INTERCULTURAL UAIIN CRIC', '9113'),
    'UNIVERSIDADES PBLICAS - UNIVERSIDAD DE ANTIOQUIA': ('UNIVERSIDAD DE ANTIOQUIA', '1201'),
    'UNIVERSIDADES PBLICAS - UNIVERSIDAD DE CARTAGENA': ('UNIVERSIDAD DE CARTAGENA', '1203'),
    'UNIVERSIDADES PBLICAS - UNIVERSIDAD DE CUNDINAMARCA': ('UNIVERSIDAD DE CUNDINAMARCA', '2104'),
    'UNIVERSIDADES PBLICAS - UNIVERSIDAD DE LA GUAJIRA': ('UNIVERSIDAD DE LA GUAJIRA', '2105'),
    'UNIVERSIDADES PBLICAS - UNIVERSIDAD DE NARIO': ('UNIVERSIDAD DE NARIÑO', '1107'),
    'UNIVERSIDADES PBLICAS - UNIVERSIDAD DE PAMPLONA': ('UNIVERSIDAD DE PAMPLONA', '1205'),
    'UNIVERSIDADES PBLICAS - UNIVERSIDAD DE SUCRE': ('UNIVERSIDAD DE SUCRE', '1119'),
    'UNIVERSIDADES PBLICAS - UNIVERSIDAD DEL ATLNTICO': ('UNIVERSIDAD DEL ATLANTICO', '1204'),
    'UNIVERSIDADES PBLICAS - UNIVERSIDAD DEL MAGDALENA': ('UNIVERSIDAD DEL MAGDALENA', '1112'),
    'UNIVERSIDADES PBLICAS - UNIVERSIDAD DEL QUINDO': ('UNIVERSIDAD DEL QUINDIO', '1111'),
    'UNIVERSIDADES PBLICAS - UNIVERSIDAD DEL TOLIMA': ('UNIVERSIDAD DEL TOLIMA', '1110'),
    'UNIVERSIDADES PBLICAS - UNIVERSIDAD DEL VALLE': ('UNIVERSIDAD DEL VALLE', '1202'),
    'UNIVERSIDADES PBLICAS - UNIVERSIDAD DISTRITAL FRANCISCO JOSE DE CALDAS': ('UNIVERSIDAD DISTRITAL FRANCISCO JOSE DE CALDAS', '2101'),
    'UNIVERSIDADES PBLICAS - UNIVERSIDAD FRANCISCO DE PAULA SANTANDER': ('UNIVERSIDAD FRANCISCO DE PAULA SANTANDER', '1108'),
    'UNIVERSIDADES PBLICAS - UNIVERSIDAD FRANCISCO DE PAULA SANTANDER SECCIONAL OCAA': ('UNIVERSIDAD FRANCISCO DE PAULA SANTANDER - OCAÑA', '1109'),
    'UNIVERSIDADES PBLICAS - UNIVERSIDAD INDUSTRIAL DE SANTANDER': ('UNIVERSIDAD INDUSTRIAL DE SANTANDER', '1206'),
    'UNIVERSIDADES PBLICAS - UNIVERSIDAD INTERNACIONAL DEL TRPICO AMERICANO': ('UNIVERSIDAD INTERNACIONAL DEL TROPICO AMERICANO', '9123'),
    'UNIVERSIDADES PBLICAS - UNIVERSIDAD MILITAR NUEVA GRANADA': ('UNIVERSIDAD MILITAR NUEVA GRANADA', '2103'),
}

def mapear_entidades():
    logger.info("=" * 65)
    logger.info("MAPEANDO CÓDIGOS IES/DANE A DIMENSIÓN DE ENTIDADES PTE")
    logger.info("=" * 65)

    if not DIM_ENTIDAD_PATH.exists():
        logger.error(f"  ❌ No se encontró dim_entidad: {DIM_ENTIDAD_PATH}")
        return False

    df = pd.read_parquet(DIM_ENTIDAD_PATH)
    logger.info(f"  Leyendo {len(df)} entidades existentes...")

    # Crear nuevas columnas usando el diccionario
    df['nombre_limpio'] = df['nombreentidad'].map(
        lambda x: MAPA_ENTIDADES.get(x, (x, '0'))[0]
    )
    df['codigo_ies'] = df['nombreentidad'].map(
        lambda x: MAPA_ENTIDADES.get(x, (x, '0'))[1]
    )

    # Identificar si alguna entidad no está en el mapa
    faltantes = df[df['nombreentidad'].map(lambda x: x not in MAPA_ENTIDADES)]
    if not faltantes.empty:
        logger.warning(f"  ⚠️ {len(faltantes)} entidades no están en el diccionario:")
        for _, row in faltantes.iterrows():
            logger.warning(f"      - {row['nombreentidad']}")

    df.to_parquet(DIM_ENTIDAD_PATH, index=False)
    logger.info(f"  ✅ Mapeo completado. Guardado en: {DIM_ENTIDAD_PATH.name}")
    logger.info("=" * 65)
    return True

if __name__ == "__main__":
    mapear_entidades()
